<script setup lang="ts">
import { computed } from "vue";
import { FileCode2, Globe } from "lucide-vue-next";

import { useCycleStep } from "@/features/release-tour/useCycleStep";

const step = useCycleStep(4, 1300);

const method = computed(() => (step.value >= 1 ? "GET" : "POST"));
const showsPage = computed(() => step.value >= 2);
const showsChip = computed(() => step.value >= 3);
</script>

<template>
  <div class="flex h-full w-full flex-col gap-2 p-3">
    <div class="flex items-center gap-2">
      <div class="flex items-center gap-1.5 rounded-md border border-primary/30 bg-primary/10 px-2 py-1">
        <FileCode2 class="h-3.5 w-3.5 text-primary" />
        <span class="text-[11px] font-semibold text-foreground">HTML output mapper</span>
      </div>
      <span
        class="rounded border px-1.5 py-0.5 text-[10px] font-semibold transition-colors duration-500"
        :class="method === 'GET'
          ? 'border-emerald-500/40 bg-emerald-500/10 text-emerald-500'
          : 'border-border bg-muted text-muted-foreground'"
      >{{ method }}</span>
    </div>

    <div class="rounded-lg border border-border bg-surface-sunken px-2 py-1.5">
      <span class="font-mono text-[10.5px] text-muted-foreground">
        curl -X <span class="text-foreground">{{ method }}</span> ".../execute?name=Ada"
      </span>
    </div>

    <div class="flex flex-1 flex-col overflow-hidden rounded-lg border border-border bg-background">
      <div class="flex items-center gap-1 border-b border-border bg-muted/50 px-2 py-1">
        <span class="h-1.5 w-1.5 rounded-full bg-muted-foreground/40" />
        <span class="h-1.5 w-1.5 rounded-full bg-muted-foreground/40" />
        <span class="ml-1 truncate font-mono text-[9.5px] text-muted-foreground">
          heym.local/api/workflows/…/execute
        </span>
      </div>
      <Transition
        enter-active-class="transition-opacity duration-500"
        enter-from-class="opacity-0"
        leave-active-class="transition-opacity duration-300"
        leave-to-class="opacity-0"
        mode="out-in"
      >
        <div
          v-if="showsPage"
          key="page"
          class="flex flex-1 flex-col items-center justify-center gap-1"
        >
          <span class="text-sm font-semibold text-foreground">Hello Ada</span>
          <span class="text-[10px] text-muted-foreground">Generated by Heym</span>
        </div>
        <div
          v-else
          key="json"
          class="flex flex-1 items-center justify-center"
        >
          <span class="font-mono text-[10.5px] text-muted-foreground">{ "page": { … } }</span>
        </div>
      </Transition>
    </div>

    <div
      class="flex items-center gap-2 rounded-lg border px-2 py-1.5 transition-all duration-500"
      :class="showsChip ? 'border-border bg-muted/40 opacity-100' : 'border-transparent opacity-0'"
    >
      <span class="truncate text-[10.5px] text-foreground">Status page</span>
      <span class="ml-auto inline-flex items-center gap-1 rounded-full bg-rose-500/10 px-2 py-0.5 text-[10px] font-medium text-rose-500 ring-1 ring-inset ring-rose-500/20">
        <Globe class="h-2.5 w-2.5" />
        WEB
      </span>
    </div>
  </div>
</template>
