import type { Component } from "vue";
import {
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  Calendar,
  Camera,
  CheckCircle2,
  ClipboardList,
  Clock,
  Cloud,
  Code2,
  Compass,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  FileText,
  Flag,
  FolderHeart,
  Gift,
  Globe,
  GraduationCap,
  Heart,
  Home,
  Inbox,
  Key,
  Layers,
  LifeBuoy,
  Lightbulb,
  Lock,
  Map,
  MessageSquare,
  Music,
  Package,
  Palette,
  PenTool,
  Plane,
  Rocket,
  Shield,
  ShoppingBag,
  Sparkles,
  Star,
  Sun,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Wallet,
  Wrench,
  Zap,
} from "lucide-vue-next";

export interface FolderIconOption {
  key: string;
  component: Component;
}

export const folderIconOptions: FolderIconOption[] = [
  { key: "Bell", component: Bell },
  { key: "BookOpen", component: BookOpen },
  { key: "Box", component: Box },
  { key: "Briefcase", component: Briefcase },
  { key: "Building2", component: Building2 },
  { key: "Calendar", component: Calendar },
  { key: "Camera", component: Camera },
  { key: "CheckCircle2", component: CheckCircle2 },
  { key: "ClipboardList", component: ClipboardList },
  { key: "Clock", component: Clock },
  { key: "Cloud", component: Cloud },
  { key: "Code2", component: Code2 },
  { key: "Compass", component: Compass },
  { key: "CreditCard", component: CreditCard },
  { key: "Crown", component: Crown },
  { key: "Database", component: Database },
  { key: "DollarSign", component: DollarSign },
  { key: "FileText", component: FileText },
  { key: "Flag", component: Flag },
  { key: "FolderHeart", component: FolderHeart },
  { key: "Gift", component: Gift },
  { key: "Globe", component: Globe },
  { key: "GraduationCap", component: GraduationCap },
  { key: "Heart", component: Heart },
  { key: "Home", component: Home },
  { key: "Inbox", component: Inbox },
  { key: "Key", component: Key },
  { key: "Layers", component: Layers },
  { key: "LifeBuoy", component: LifeBuoy },
  { key: "Lightbulb", component: Lightbulb },
  { key: "Lock", component: Lock },
  { key: "Map", component: Map },
  { key: "MessageSquare", component: MessageSquare },
  { key: "Music", component: Music },
  { key: "Package", component: Package },
  { key: "Palette", component: Palette },
  { key: "PenTool", component: PenTool },
  { key: "Plane", component: Plane },
  { key: "Rocket", component: Rocket },
  { key: "Shield", component: Shield },
  { key: "ShoppingBag", component: ShoppingBag },
  { key: "Sparkles", component: Sparkles },
  { key: "Star", component: Star },
  { key: "Sun", component: Sun },
  { key: "Target", component: Target },
  { key: "TrendingUp", component: TrendingUp },
  { key: "Trophy", component: Trophy },
  { key: "Users", component: Users },
  { key: "Wallet", component: Wallet },
  { key: "Wrench", component: Wrench },
  { key: "Zap", component: Zap },
];

const folderIconMap: Record<string, Component> = Object.fromEntries(
  folderIconOptions.map((option) => [option.key, option.component]),
);

export function getFolderIcon(key: string | null | undefined): Component | null {
  if (!key) return null;
  return folderIconMap[key] ?? null;
}
